[build]
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/easy.html"
  to = "/easy.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"